nmMode: hardlinks-local

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-publishconfig.cjs
    spec: "https://raw.githubusercontent.com/alizeait/yarn-plugin-publishconfig/v1.0/bundles/@yarnpkg/plugin-publishconfig.js"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
